// <auto-generated />
using System;
using Backend.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.API.Data.Context.Migrations
{
    [DbContext(typeof(EndlessContext))]
    [Migration("20260308153542_UserAndDomainSubscriptionsAndVideoMeta")]
    partial class UserAndDomainSubscriptionsAndVideoMeta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.API.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<long>("DizLikeCount")
                        .HasColumnType("bigint");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublicatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommentatorId");

                    b.HasIndex("ContentId");

                    b.HasIndex("PublicatedDate");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<string>("ContentUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("DizLikeCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DomainId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalLikes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DomainOwner", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OwnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OwnerRole")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "DomainId");

                    b.HasIndex("DomainId");

                    b.ToTable("DomainOwners");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DomainSubscription", b =>
                {
                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Notification")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubscribedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriberId", "DomainId");

                    b.HasIndex("DomainId");

                    b.ToTable("DomainSubscription");
                });

            modelBuilder.Entity("Backend.API.Data.Models.LikedContent", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegistryDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("LikedContents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.SavedContent", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegistryDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("SavedContents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrivateType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistryData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalLikes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.API.Data.Models.UserSubscribtion", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FollowedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Notification")
                        .HasColumnType("boolean");

                    b.HasKey("FollowerId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscribtion");
                });

            modelBuilder.Entity("Backend.API.Data.Models.VideoMetaData", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.HasKey("ContentId");

                    b.ToTable("VideoMetas");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Comment", b =>
                {
                    b.HasOne("Backend.API.Data.Models.User", "Commentator")
                        .WithMany("Comments")
                        .HasForeignKey("CommentatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("Comments")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentator");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.HasOne("Backend.API.Data.Models.User", "Creator")
                        .WithMany("Contents")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.Domain", "Domain")
                        .WithMany("Contents")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DomainOwner", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Domain", "Domain")
                        .WithMany("Owners")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("Owners")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DomainSubscription", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Domain", "Domain")
                        .WithMany("Subsrcibers")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "SubscribedUser")
                        .WithMany("DomainSubscriptions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("SubscribedUser");
                });

            modelBuilder.Entity("Backend.API.Data.Models.LikedContent", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("ContentLikeds")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "Owner")
                        .WithMany("LikedContents")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Backend.API.Data.Models.SavedContent", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("ContentSaveds")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "Owner")
                        .WithMany("SavedContents")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.OwnsOne("Backend.API.Data.Components.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("ValidityPeriod")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("Backend.API.Data.Models.UserSubscribtion", b =>
                {
                    b.HasOne("Backend.API.Data.Models.User", "FollowedUser")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("Following")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.VideoMetaData", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithOne("VideoMeta")
                        .HasForeignKey("Backend.API.Data.Models.VideoMetaData", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ContentLikeds");

                    b.Navigation("ContentSaveds");

                    b.Navigation("VideoMeta");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Domain", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Owners");

                    b.Navigation("Subsrcibers");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Contents");

                    b.Navigation("DomainSubscriptions");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("LikedContents");

                    b.Navigation("Owners");

                    b.Navigation("SavedContents");
                });
#pragma warning restore 612, 618
        }
    }
}
