// <auto-generated />
using System;
using Backend.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.API.Data.Context.Migrations
{
    [DbContext(typeof(EndlessContext))]
    [Migration("20260307220047_NewColumnsInDomainUserContentComment")]
    partial class NewColumnsInDomainUserContentComment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.API.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<long>("DizLikeCount")
                        .HasColumnType("bigint");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommentatorId");

                    b.HasIndex("ContentId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DizLikeCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.Property<int>("contentType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CraetedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalLikes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistryData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<long>("TotalLikes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DomainUser", b =>
                {
                    b.Property<Guid>("DomainsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnersId")
                        .HasColumnType("uuid");

                    b.HasKey("DomainsId", "OwnersId");

                    b.HasIndex("OwnersId");

                    b.ToTable("DomainsOwners", (string)null);
                });

            modelBuilder.Entity("DomainUser1", b =>
                {
                    b.Property<Guid>("SignedDomainsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SignedUsersId")
                        .HasColumnType("uuid");

                    b.HasKey("SignedDomainsId", "SignedUsersId");

                    b.HasIndex("SignedUsersId");

                    b.ToTable("DomainSigned", (string)null);
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<Guid>("SubscribesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionsId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscribesId", "SubscriptionsId");

                    b.HasIndex("SubscriptionsId");

                    b.ToTable("UserSubscription", (string)null);
                });

            modelBuilder.Entity("Backend.API.Data.Models.Comment", b =>
                {
                    b.HasOne("Backend.API.Data.Models.User", "Commentator")
                        .WithMany("Comments")
                        .HasForeignKey("CommentatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("Comments")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentator");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Domain", "Domain")
                        .WithMany("Contents")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", null)
                        .WithMany("LikedContent")
                        .HasForeignKey("UserId");

                    b.HasOne("Backend.API.Data.Models.User", null)
                        .WithMany("SavedContent")
                        .HasForeignKey("UserId1");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.OwnsOne("Backend.API.Data.Components.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("ValidityPeriod")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("DomainUser", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Domain", null)
                        .WithMany()
                        .HasForeignKey("DomainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainUser1", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Domain", null)
                        .WithMany()
                        .HasForeignKey("SignedDomainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SignedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("Backend.API.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubscribesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Domain", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("LikedContent");

                    b.Navigation("SavedContent");
                });
#pragma warning restore 612, 618
        }
    }
}
