// <auto-generated />
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Backend.API.Data.Context;
using System;

#nullable disable

namespace Backend.API.Data.Context.Migrations
{
    [DbContext(typeof(EndlessContext))]
    partial class EndlessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.API.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublicatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommentatorId");

                    b.HasIndex("ContentId");

                    b.HasIndex("PublicatedDate");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<string>("ContentUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrewievPhotoUrl")
                        .HasColumnType("text");

                    b.Property<double>("RandomKey")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Slug")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DomainId");

                    b.HasIndex("RandomKey");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.ContentGenreVector", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.Property<float>("AudienceVector")
                        .HasColumnType("real");

                    b.Property<float>("AuthorVector")
                        .HasColumnType("real");

                    b.Property<float>("FinalVector")
                        .HasColumnType("real");

                    b.HasKey("ContentId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ContentVectors");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DizLikedComment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DizLikedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("DizLikedComments");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DizLikedContent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DizLikedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("DizLikedContents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarPhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalLikes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DomainOwner", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OwnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OwnerRole")
                        .HasColumnType("integer");

                    b.HasKey("OwnerId", "DomainId");

                    b.HasIndex("DomainId");

                    b.ToTable("DomainOwners");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DomainSubscription", b =>
                {
                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Notification")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubscribedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriberId", "DomainId");

                    b.HasIndex("DomainId");

                    b.ToTable("DomainSubscriptions");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Backend.API.Data.Models.GenreInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GenreInfos");
                });

            modelBuilder.Entity("Backend.API.Data.Models.LikedComment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LikedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("LikedComments");
                });

            modelBuilder.Entity("Backend.API.Data.Models.LikedContent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LikedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("LikedContents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.SavedContent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("SavedContents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarPhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrivateType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistryData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalLikes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.API.Data.Models.UserFollowing", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FollowedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Notification")
                        .HasColumnType("boolean");

                    b.HasKey("FollowerId", "FollowedUserId");

                    b.HasIndex("FollowedUserId");

                    b.ToTable("UserFollowings");
                });

            modelBuilder.Entity("Backend.API.Data.Models.UserGenreVector", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("UserId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("UserVectors");
                });

            modelBuilder.Entity("Backend.API.Data.Models.UserInterationContent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Liked")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saved")
                        .HasColumnType("boolean");

                    b.Property<int>("WatchTimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("UserInterationContents");
                });

            modelBuilder.Entity("Backend.API.Data.Models.VideoMetaData", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<float>("AverageWatchRatio")
                        .HasColumnType("real");

                    b.Property<int>("AverageWatchTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.HasKey("ContentId");

                    b.ToTable("VideoMetas");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Comment", b =>
                {
                    b.HasOne("Backend.API.Data.Models.User", "Commentator")
                        .WithMany("Comments")
                        .HasForeignKey("CommentatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("Comments")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentator");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.HasOne("Backend.API.Data.Models.User", "Creator")
                        .WithMany("Contents")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.Domain", "Domain")
                        .WithMany("Contents")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Backend.API.Data.Models.ContentGenreVector", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("Vectors")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DizLikedComment", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Comment", "Comment")
                        .WithMany("DizLikers")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("DizLikedComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DizLikedContent", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("DizLikers")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("DizLikedContents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DomainOwner", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Domain", "Domain")
                        .WithMany("Owners")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "Owner")
                        .WithMany("OwnedDomains")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Backend.API.Data.Models.DomainSubscription", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Domain", "Domain")
                        .WithMany("Subscribers")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "Subscriber")
                        .WithMany("SubscripedDomains")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("Backend.API.Data.Models.LikedComment", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Comment", "Comment")
                        .WithMany("Likers")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("LikedComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.LikedContent", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("Likers")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("LikedContents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.SavedContent", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("Savers")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("SavedContents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.OwnsOne("Backend.API.Data.Components.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("ValidityPeriod")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("Backend.API.Data.Models.UserFollowing", b =>
                {
                    b.HasOne("Backend.API.Data.Models.User", "FollowedUser")
                        .WithMany("Following")
                        .HasForeignKey("FollowedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "Follower")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedUser");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Backend.API.Data.Models.UserGenreVector", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("Vectors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.UserInterationContent", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithMany("UsersInteration")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.API.Data.Models.User", "User")
                        .WithMany("UserInterations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.API.Data.Models.VideoMetaData", b =>
                {
                    b.HasOne("Backend.API.Data.Models.Content", "Content")
                        .WithOne("VideoMeta")
                        .HasForeignKey("Backend.API.Data.Models.VideoMetaData", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Comment", b =>
                {
                    b.Navigation("DizLikers");

                    b.Navigation("Likers");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Content", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DizLikers");

                    b.Navigation("Likers");

                    b.Navigation("Savers");

                    b.Navigation("UsersInteration");

                    b.Navigation("Vectors");

                    b.Navigation("VideoMeta");
                });

            modelBuilder.Entity("Backend.API.Data.Models.Domain", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Owners");

                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("Backend.API.Data.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Contents");

                    b.Navigation("DizLikedComments");

                    b.Navigation("DizLikedContents");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("LikedComments");

                    b.Navigation("LikedContents");

                    b.Navigation("OwnedDomains");

                    b.Navigation("SavedContents");

                    b.Navigation("SubscripedDomains");

                    b.Navigation("UserInterations");

                    b.Navigation("Vectors");
                });
#pragma warning restore 612, 618
        }
    }
}
