name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run Tests
      run: docker build -f docker/Dockerfile --target test-runner -t endless-tests .

    - name: Create license file
      run: echo "${{ secrets.SIXLABORS_LICENSE }}" > sixlabors.lic

    - name: Build Final
      run: docker compose build